---
title: "Lab 4"
output: github_document
allways_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

## 1. Read in the data

```{r}
if (!file.exists("../met_all.gz"))
  download.file(
    url = "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
    destfile = "../met_all.gz",
    method   = "libcurl",
    timeout  = 60
    )
met <- data.table::fread("../met_all.gz")
```

## 2. Prepare the data

```{r data-prep}
# Remove temperatures less than -17C
met <- met[temp >= -17]

# Make sure there are no missing data in the key variables coded as 9999, 999, etc
# temp, rh, wind.sp, vis.dist, dew.point, lat, lon, and elev.
met[, range(temp)]
met[, range(rh, na.rm = TRUE)]
met[, range(wind.sp, na.rm = TRUE)]
met[, range(vis.dist, na.rm = TRUE)]
met[, range(dew.point, na.rm = TRUE)]
met[, range(lat, na.rm = TRUE)]
met[, range(lon, na.rm = TRUE)]
met[, range(elev, na.rm = TRUE)]

met[elev == 9999.0, elev := NA]

# Generate a date variable using the functions as.Date()
# (hint: You will need the following to create a date paste(year, month, day, sep = "-")).
met[, ymd := as.Date(paste(year, month, day, sep = "-"))]

# Using the data.table::week function, keep the observations of
# the first week of the month.
met[, table(week(ymd))]
met <- met[ week(ymd) == 31]

# Compute the mean by station of the variables temp, rh, wind.sp, vis.dist, dew.point, lat, lon, and elev.
met_avg <- met[, .(
  temp      = mean(temp, na.rm = TRUE),
  rh        = mean(rh, na.rm = TRUE),
  wind.sp   = mean(wind.sp, na.rm = TRUE),
  vis.dist  = mean(vis.dist, na.rm = TRUE),
  dew.point = mean(dew.point, na.rm = TRUE),
  lat       = mean(lat, na.rm = TRUE),
  lon       = mean(lon, na.rm = TRUE),
  elev      = mean(elev, na.rm = TRUE), USAFID
), by = "USAFID"]

# Create a region variable for NW, SW, NE, SE based on lon = -98.00 and lat = 39.71 degrees
# Create a categorical variable for elevation as in the lecture slides

```


